version: '3'

networks:
  datalake-nw:
    external: true

services:
  hive:
    container_name: hive
    hostname: hive
    # image: arshadansari27/hive:latest
    build:
      context: ..
      dockerfile: hive/Dockerfile
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
      - HIVE_HOME=/usr/local/hive
    # healthcheck:
    #   test: [ "CMD", "sh", "-c", "nc -z hive 10001" ]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 10
    networks:
      - datalake-nw

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - datalake-nw
