version: "3"

services:
  hive:
    container_name: hive
    hostname: hive
    # image: arshadansari27/hive:latest
    build:
      context: ..
      dockerfile: hive/Dockerfile
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
      - HIVE_HOME=/usr/local/hive

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 20s
      timeout: 10s
      retries: 10
